version: '2.0'
services:
  server:
    ports:
    - "3001:3001"
    volumes:
      - "./server/:/srv/app"
    environment:
    - "PORT=3001"
  front:
    ports:
    - "3000:3000"
    volumes:
    - "./front/:/srv/app"